# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('normal', models.CharField(max_length=5000)),
                ('abnormal', models.CharField(max_length=5000)),
                ('peers', models.CharField(max_length=5000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('AS', models.CharField(max_length=100)),
                ('ISP', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('route', models.CharField(max_length=5000)),
                ('latest_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(default='', max_length=100)),
                ('srcIP', models.CharField(default='', max_length=100)),
                ('dst', models.CharField(default='', max_length=100)),
                ('dstIP', models.CharField(default='', max_length=100)),
                ('latest_check', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('region', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('AS', models.CharField(default='', max_length=100)),
                ('ISP', models.CharField(default='', max_length=200)),
                ('longitude', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('clients', models.CharField(default='', max_length=5000)),
                ('latest_check', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
