# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalyLocator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='route',
        ),
        migrations.AlterField(
            model_name='node',
            name='AS',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='ISP',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='node',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='region',
            field=models.CharField(default='', max_length=100),
        ),
    ]
